### ISSUE TITLE
Can't launch the game properly

### ISSUE THREAD

**Issue by Rockefeller157** [anno-mods/Anno#1]
Hello.
I recently tried this mod manager and it seems it works fine for adding or deleting mods from the dedicated folder.

However, it appears that this mod manager actually also changes the mod loader, and cause the game to crash without showing any error. 

Putting the normal mod loader (https://github.com/xforce/anno1800-mod-loader) solved the problem.

Thanks for your time.

**Comment by akkzockt** [comment]
Hey,  Thanks for your feedback. 

Actually **Mod Manager** uses the latest **Mod Loader** and copies it to your game folder by pressing **'Loader Deactived'** to **'Loader Active'** button.

If you downloaded **Mod Loader** manually before, you can check the file properties of **python35.dll** and you will see that this file is ***Read-only***. When the **Manager** wants to copy/remove files (by pressing the **'Loader...'** button) you get that error you report. 

I would recommend you to remove the ***Read-only*** attribute, so you can use the **Manager** to enable/disable the **Loader** without errors.

The **Manager** removes this ***Read-only*** attribute automatically when downloading it (you can find it here: menu **Loader** -> **Open Folder**).

I hope that helps you.

**Comment by akkzockt** [comment]
Fixed in **v0.2.2** - **Mod Manager** will remove ***Read-only*** attribute of **python35.dll**.
