### ISSUE TITLE
Can't start Anno 1800 with Mod Manager

### ISSUE THREAD

**Issue by Zyno448** [anno-mods/Anno#3]
I selected my mod then active the loader but when I click on "Start Anno 1800" the game doesn't start.
Im waiting for 15 minutes and the game didn't start

**Comment by akkzockt** [comment]
You are absolutely right. Mod Loader needs an update. As soon as a new version is released, Mod Manager will automatically update it, too. Currently there is a Pre-Release for the next Mod Loader available. So it won't be long now and it will be fine.

**Comment by akkzockt** [comment]
@xforce we are waiting for your release :sunglasses:

**Comment by akkzockt** [comment]
Thanks for the Mod Loader release.
