### ISSUE TITLE
[Suggestion] Mod configuration

### ISSUE THREAD

**Issue by Serpens66** [anno-mods/Anno#9]
For more complex mods (with more than one xml file), I would sugget mod-configuration.

For example a mod that changes Item/goods prices. A perfect modsetting would be to allow the user to define a multiplier, regardless which value. This value will then multiply all prices.
Not sure if this is currently possible. I don't know if you can write variables in xml or if sql will work or whatever.
But I'm sure this is possible somehow.

If no variable value is possible, then we could use instead preconfigered opitions, like easy,medium,hard and set the mutlipler to eg. 0.75, 1.25 and 2 and add 3 xml files from which the mod loader only will load one. But the way with variable would be better of course.

Even if my example may not be the best, I'm sure there are good use-cases for such modsettings.

**Comment by akkzockt** [comment]
Thanks for your detailed suggestion. Maybe it is something for the new Manager that is currently under development:

https://github.com/LemonDrop1228/anno1800-mod-manager
https://github.com/LemonDrop1228/AMM-Source-Code
